export const zodiac = [
  {
    id: '1',
    name: 'aquarius',
    dates: 'Jan 21 - Feb 19',
    symbol: 'Water Bearer',
    top: '200px',
    left: '0',
  },
  {
    id: '2',
    name: 'aries',
    dates: 'Mar 21 - Apr 19',
    symbol: 'Ram',
    top: '500px',
    left: '0',
  },
  {
    id: '3',
    name: 'cancer',
    dates: 'Jun 21 - Jul 22',
    symbol: 'Crab',
    top: '800px',
    left: '0',
  },
  {
    id: '4',
    name: 'capricorn',
    dates: 'Dec 22 - Feb 19',
    symbol: 'Goat',
    top: '200px',
    left: '25%',
  },
  {
    id: '5',
    name: 'gemini',
    dates: 'May 21 - Jun 20',
    symbol: 'Twins',
    top: '500px',
    left: '25%',
  },
  {
    id: '6',
    name: 'leo',
    dates: 'Jul 23 - Aug 22',
    symbol: 'Lion',
    top: '800px',
    left: '25%',
  },
  {
    id: '7',
    name: 'libra',
    dates: 'Sept 23 - Oct 22',
    symbol: 'Balance',
    top: '200px',
    left: '50%',
  },
  {
    id: '8',
    name: 'pisces',
    dates: 'Feb 19 - Mar 20',
    symbol: 'Fish',
    top: '500px',
    left: '50%',
  },
  {
    id: '9',
    name: 'sagittarius',
    dates: 'Nov 22 - Dec 21',
    symbol: 'Archer',
    top: '800px',
    left: '50%',
  },
  {
    id: '10',
    name: 'scorpio',
    dates: 'Oct 23 - Nov 21',
    symbol: 'Scorpion',
    top: '200px',
    left: '75%',
  },
  {
    id: '11',
    name: 'taurus',
    dates: 'Apr 20 - May 20',
    symbol: 'Bull',
    top: '500px',
    left: '75%',
  },
  {
    id: '12',
    name: 'virgo',
    dates: 'Aug 23 - Sep 22',
    symbol: 'Virgin',
    top: '800px',
    left: '75%',
  },
  {
    id: '13',
    name: 'ophiuchus',
    dates: 'none',
    symbol: 'Serpent',
    left: '45%',
  },
];
